<?php
/**
 * Interfaz de Cliente de IA - Monday's Work AI Core
 * AI Client Interface - Monday's Work AI Core
 *
 * Define el contrato que deben cumplir todos los clientes de IA
 * del sistema. Esta interfaz asegura consistencia entre diferentes
 * proveedores (OpenAI, Anthropic, etc.) y facilita la intercambiabilidad
 * de implementaciones.
 *
 * Defines the contract that all AI clients in the system must fulfill.
 * This interface ensures consistency across different providers
 * (OpenAI, Anthropic, etc.) and facilitates implementation interchangeability.
 *
 * @package    MondaysWork\AI\Core
 * @subpackage AI
 * @since      1.0.0
 * @author     Mondays at Work <info@mondaysatwork.com>
 */

namespace MondaysWork\AI\Core\AI;

// Evitar acceso directo / Prevent direct access
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Interfaz de Cliente de IA
 * AI Client Interface
 *
 * Define los métodos que debe implementar cualquier cliente de IA
 * para integrarse con el sistema. Proporciona una API consistente
 * independientemente del proveedor subyacente.
 *
 * Defines methods that any AI client must implement
 * to integrate with the system. Provides a consistent API
 * regardless of the underlying provider.
 *
 * @since 1.0.0
 */
interface AIClientInterface {

    /**
     * Genera texto basado en un prompt
     * Generates text based on a prompt
     *
     * Este método es la forma más básica de interactuar con la IA.
     * Envía un prompt de texto y recibe una respuesta generada.
     * Útil para completar textos, generar descripciones, o crear contenido.
     *
     * This is the most basic way to interact with the AI.
     * Sends a text prompt and receives a generated response.
     * Useful for text completion, generating descriptions, or creating content.
     *
     * Ejemplo de uso / Usage example:
     * ```php
     * $client = new OpenAIClient($config);
     * $response = $client->generateText(
     *     'Escribe una descripción de producto para unas zapatillas deportivas',
     *     ['temperature' => 0.7, 'max_tokens' => 150]
     * );
     * ```
     *
     * @since  1.0.0
     * @access public
     *
     * @param  string $prompt Texto de entrada para la IA / Input text for the AI
     *                        Debe ser un string no vacío con la instrucción o contexto.
     *                        Must be a non-empty string with the instruction or context.
     *
     * @param  array  $params Parámetros opcionales de generación / Optional generation parameters
     *                        Puede incluir / May include:
     *                        - 'temperature' (float): Creatividad de la respuesta (0.0-2.0)
     *                                                Creativity of response (0.0-2.0)
     *                        - 'max_tokens' (int): Número máximo de tokens a generar
     *                                             Maximum number of tokens to generate
     *                        - 'top_p' (float): Nucleus sampling (0.0-1.0)
     *                        - 'frequency_penalty' (float): Penalización por repetición (-2.0-2.0)
     *                                                      Repetition penalty (-2.0-2.0)
     *                        - 'presence_penalty' (float): Penalización por presencia (-2.0-2.0)
     *                                                     Presence penalty (-2.0-2.0)
     *                        - 'stop' (array): Secuencias donde detener la generación
     *                                         Sequences where to stop generation
     *
     * @return string         Texto generado por la IA / Text generated by the AI
     *                        Retorna el contenido de texto generado.
     *                        Returns the generated text content.
     *
     * @throws \Exception     Si hay un error en la comunicación con la API
     *                        If there's an error communicating with the API
     * @throws \InvalidArgumentException Si el prompt está vacío o los parámetros son inválidos
     *                                  If the prompt is empty or parameters are invalid
     */
    public function generateText( string $prompt, array $params = array() ): string;

    /**
     * Mantiene una conversación con mensajes múltiples
     * Maintains a conversation with multiple messages
     *
     * Permite interacciones conversacionales más complejas con contexto.
     * Soporta roles de usuario y asistente para mantener el hilo de conversación.
     * Ideal para chatbots, asistentes virtuales o interfaces conversacionales.
     *
     * Allows more complex conversational interactions with context.
     * Supports user and assistant roles to maintain conversation thread.
     * Ideal for chatbots, virtual assistants, or conversational interfaces.
     *
     * Ejemplo de uso / Usage example:
     * ```php
     * $messages = [
     *     ['role' => 'system', 'content' => 'Eres un experto en ecommerce'],
     *     ['role' => 'user', 'content' => '¿Cómo optimizo mi página de producto?'],
     *     ['role' => 'assistant', 'content' => 'Te recomiendo...'],
     *     ['role' => 'user', 'content' => '¿Y las imágenes?']
     * ];
     * $response = $client->chat($messages, ['temperature' => 0.8]);
     * ```
     *
     * @since  1.0.0
     * @access public
     *
     * @param  array $messages Array de mensajes de conversación / Array of conversation messages
     *                         Cada mensaje debe tener la estructura / Each message must have structure:
     *                         [
     *                             'role' => 'system'|'user'|'assistant',
     *                             'content' => 'Texto del mensaje / Message text'
     *                         ]
     *                         - 'system': Instrucciones del sistema / System instructions
     *                         - 'user': Mensaje del usuario / User message
     *                         - 'assistant': Respuesta previa de la IA / Previous AI response
     *
     * @param  array $params   Parámetros opcionales / Optional parameters
     *                         Los mismos que generateText() más / Same as generateText() plus:
     *                         - 'stream' (bool): Transmitir respuesta en tiempo real
     *                                           Stream response in real-time
     *                         - 'functions' (array): Definiciones de funciones para llamadas
     *                                               Function definitions for calls
     *
     * @return string          Respuesta generada por la IA / Response generated by the AI
     *                         Retorna solo el contenido del mensaje de respuesta.
     *                         Returns only the response message content.
     *
     * @throws \Exception      Si hay un error en la comunicación con la API
     *                         If there's an error communicating with the API
     * @throws \InvalidArgumentException Si el array de mensajes está vacío o mal formateado
     *                                  If the messages array is empty or malformed
     */
    public function chat( array $messages, array $params = array() ): string;

    /**
     * Analiza texto y extrae información estructurada
     * Analyzes text and extracts structured information
     *
     * Realiza análisis semántico, extracción de entidades, clasificación
     * o cualquier otro tipo de procesamiento que devuelva datos estructurados.
     * Útil para análisis de sentimiento, extracción de keywords, categorización, etc.
     *
     * Performs semantic analysis, entity extraction, classification,
     * or any other processing that returns structured data.
     * Useful for sentiment analysis, keyword extraction, categorization, etc.
     *
     * Ejemplo de uso / Usage example:
     * ```php
     * $text = 'Este producto es excelente, llegó rápido y bien empaquetado';
     * $analysis = $client->analyzeText($text);
     * // Retorna: ['sentiment' => 'positive', 'score' => 0.95, 'entities' => [...]]
     * ```
     *
     * @since  1.0.0
     * @access public
     *
     * @param  string $text    Texto a analizar / Text to analyze
     *                         Debe ser un string no vacío con el contenido a procesar.
     *                         Must be a non-empty string with the content to process.
     *
     * @return array           Resultados del análisis / Analysis results
     *                         Estructura típica / Typical structure:
     *                         [
     *                             'sentiment' => 'positive'|'neutral'|'negative',
     *                             'score' => float (0.0-1.0),
     *                             'entities' => [
     *                                 ['text' => string, 'type' => string, 'confidence' => float],
     *                                 ...
     *                             ],
     *                             'keywords' => [string, ...],
     *                             'categories' => [string, ...],
     *                             'language' => string (ISO 639-1 code),
     *                             'metadata' => [key => value, ...]
     *                         ]
     *                         La estructura exacta puede variar según el proveedor.
     *                         Exact structure may vary by provider.
     *
     * @throws \Exception      Si hay un error en la comunicación con la API
     *                         If there's an error communicating with the API
     * @throws \InvalidArgumentException Si el texto está vacío
     *                                  If the text is empty
     */
    public function analyzeText( string $text ): array;

    /**
     * Prueba la conexión con el servicio de IA
     * Tests the connection with the AI service
     *
     * Verifica que las credenciales sean válidas, el servicio esté disponible
     * y el cliente pueda realizar peticiones exitosamente. Útil para validación
     * de configuración y diagnóstico de problemas.
     *
     * Verifies that credentials are valid, the service is available,
     * and the client can make successful requests. Useful for configuration
     * validation and troubleshooting.
     *
     * Ejemplo de uso / Usage example:
     * ```php
     * $client = new OpenAIClient($config);
     * if ($client->testConnection()) {
     *     echo 'Conexión exitosa';
     * } else {
     *     echo 'Error de conexión';
     * }
     * ```
     *
     * @since  1.0.0
     * @access public
     *
     * @return bool            True si la conexión es exitosa / True if connection is successful
     *                         False si hay problemas de conectividad o autenticación.
     *                         False if there are connectivity or authentication issues.
     *
     * @throws \Exception      Puede lanzar excepción con detalles del error
     *                         May throw exception with error details
     */
    public function testConnection(): bool;

    /**
     * Obtiene el modelo de IA actual
     * Gets the current AI model
     *
     * Devuelve el identificador del modelo que está siendo utilizado
     * actualmente para las peticiones. Los identificadores varían según
     * el proveedor (ej: 'gpt-4', 'claude-3-opus', 'llama-2-70b').
     *
     * Returns the identifier of the model currently being used
     * for requests. Identifiers vary by provider
     * (e.g., 'gpt-4', 'claude-3-opus', 'llama-2-70b').
     *
     * Ejemplo de uso / Usage example:
     * ```php
     * $current_model = $client->getModel();
     * echo "Using model: " . $current_model; // "Using model: gpt-4"
     * ```
     *
     * @since  1.0.0
     * @access public
     *
     * @return string          Identificador del modelo / Model identifier
     *                         Ejemplo: 'gpt-4', 'gpt-3.5-turbo', 'claude-3-opus-20240229'
     *                         Example: 'gpt-4', 'gpt-3.5-turbo', 'claude-3-opus-20240229'
     */
    public function getModel(): string;

    /**
     * Establece el modelo de IA a utilizar
     * Sets the AI model to use
     *
     * Cambia el modelo de IA que se utilizará para las siguientes peticiones.
     * Cada proveedor tiene sus propios modelos disponibles con diferentes
     * capacidades, velocidades y costos.
     *
     * Changes the AI model to be used for subsequent requests.
     * Each provider has its own available models with different
     * capabilities, speeds, and costs.
     *
     * Ejemplo de uso / Usage example:
     * ```php
     * $client->setModel('gpt-4-turbo');
     * // Ahora todas las peticiones usarán GPT-4 Turbo
     * // Now all requests will use GPT-4 Turbo
     * ```
     *
     * @since  1.0.0
     * @access public
     *
     * @param  string $model   Identificador del modelo / Model identifier
     *                         Debe ser un modelo válido del proveedor.
     *                         Must be a valid provider model.
     *                         Ejemplos / Examples:
     *                         - OpenAI: 'gpt-4', 'gpt-3.5-turbo', 'gpt-4-turbo'
     *                         - Anthropic: 'claude-3-opus-20240229', 'claude-3-sonnet-20240229'
     *
     * @return void
     *
     * @throws \InvalidArgumentException Si el modelo no es válido para el proveedor
     *                                  If the model is not valid for the provider
     */
    public function setModel( string $model ): void;

    /**
     * Obtiene el límite máximo de tokens
     * Gets the maximum token limit
     *
     * Devuelve el número máximo de tokens que se generarán en las respuestas.
     * Un token es aproximadamente 4 caracteres en inglés o 1-2 caracteres en español.
     * Este límite ayuda a controlar costos y longitud de respuestas.
     *
     * Returns the maximum number of tokens that will be generated in responses.
     * A token is approximately 4 characters in English or 1-2 characters in Spanish.
     * This limit helps control costs and response length.
     *
     * Ejemplo de uso / Usage example:
     * ```php
     * $max_tokens = $client->getMaxTokens();
     * echo "Límite actual: " . $max_tokens; // "Límite actual: 1000"
     * ```
     *
     * @since  1.0.0
     * @access public
     *
     * @return int             Número máximo de tokens / Maximum number of tokens
     *                         Típicamente entre 100-4000 dependiendo del uso.
     *                         Typically between 100-4000 depending on use case.
     */
    public function getMaxTokens(): int;

    /**
     * Establece el límite máximo de tokens
     * Sets the maximum token limit
     *
     * Define cuántos tokens como máximo puede generar la IA en sus respuestas.
     * Valores más bajos = respuestas más cortas y económicas.
     * Valores más altos = respuestas más largas pero más costosas.
     *
     * Defines how many tokens at most the AI can generate in its responses.
     * Lower values = shorter, more economical responses.
     * Higher values = longer but more expensive responses.
     *
     * Ejemplo de uso / Usage example:
     * ```php
     * $client->setMaxTokens(500);
     * // Ahora las respuestas tendrán máximo 500 tokens (~2000 caracteres)
     * // Now responses will have a maximum of 500 tokens (~2000 characters)
     * ```
     *
     * @since  1.0.0
     * @access public
     *
     * @param  int $tokens     Número máximo de tokens / Maximum number of tokens
     *                         Debe ser un entero positivo.
     *                         Must be a positive integer.
     *                         Límites típicos / Typical limits:
     *                         - Mínimo recomendado / Recommended minimum: 50
     *                         - Máximo común / Common maximum: 4096
     *                         - Algunos modelos soportan hasta 32000+
     *                           Some models support up to 32000+
     *
     * @return void
     *
     * @throws \InvalidArgumentException Si el número de tokens es inválido
     *                                  If the number of tokens is invalid
     */
    public function setMaxTokens( int $tokens ): void;
}
